CREATE USER gravity IDENTIFIED BY mypassword;

GRANT CONNECT TO gravity;
GRANT CREATE SESSION TO gravity;
GRANT UNLIMITED TABLESPACE TO gravity;
GRANT CREATE TABLE TO gravity;
GRANT CREATE SEQUENCE TO gravity;
